### ISSUE TITLE
Testing/Helping

### ISSUE THREAD

**Issue by jasonmj** [pappersverk/inky#1]
Hi there, I've just purchased an Inky phat for my rpi0 and I'm trying to get your repo to work. I wanted to reach out to you and see how this project is coming along and if there's anything I can do to test/help out? 

I've got the yellow version of the Inky phat. So far, I've added this repo as a dependency to a basic Nerves sandbox and I'm able to interact with with it over ssh in an iex session. 

I ran the few commands I saw in the "Examples" comment under Inky.ex and all went well until I ran Inky.show(state). 

`iex(20)> Inky.show(state)
"send_command/2"
"spi_write/3 binary"
** (MatchError) no match of right hand side value: {:error, :timeout}
    (inky_zero_nerves) lib/inky/inky.ex:279: Inky.spi_write/3
    (inky_zero_nerves) lib/inky/inky.ex:85: Inky.setup/2
    (inky_zero_nerves) lib/inky/inky.ex:135: Inky.update/3`

I haven't got time right now to dig in further and see if I can get this to work, but I would like to spend some time playing with it over the holidays. I figured it'd be good to drop you a line and say hi before I got to tinkering with it. 

Anyhow, I'll see what I can do on my own over the next few days and check back later with a progress report. Until then, thanks for the work you've done here!

**Comment by jasonmj** [comment]
Hello again, I ended up forking this repo and pushing a few commits that allowed me to update the screen using `Inky.show(state)` after setting the state with `Inky.setup(nil, :phat)`. I also started working on an umbrella app that uses my fork as a target dep alongside Mogrify with the goal of displaying an image. I've still got a long way to go there, but I wanted to let you know I've made a little progress. Here's the fork: 

https://github.com/jasonmj/inky_zero_nerves

**Comment by lawik** [comment]
Oh, sorry for not answering, I haven't been keeping tabs on my GitHub notifications.

You got it to show things? Then you might have solved whatever problem I was having because I had not made it work right yet. Wow! I have to check out your fix when I have a moment :)

**Comment by lawik** [comment]
I checked your commits. Seems I wasn't far from getting it going. Would you mind cooking up a PR and a way to select red/yellow and we can merge back in. I'm happy to cooperate on getting this as far as possible with whatever time we have. I don't particularly care which repo we work in to be honest :)

**Comment by lawik** [comment]
I'll hook you up with access if you're up for it.

**Comment by lawik** [comment]
I've merged your changes to this master.

**Comment by jasonmj** [comment]
Awesome, thanks Lars! I haven't had much time to work on Nerves projects
since the start of the year. I've got another project I'm putting time into
now, but I hope to get back to Inky Nerves sometime in the next few weeks.

I'd be happy to continue developing the library with you. I don't
particularly care which repo we use, but it probably makes more sense to
use the one you created.

 I'm on Elixir Slack and in the Elixir Forum every now and then. Keep in
touch!

-=-
Jason Johnson
FullSteam Labs
828.202.5300

**Comment by lawik** [comment]
I know how it can be, with projects and fun things.

I'll add you to this repo.
