### ISSUE TITLE
GenServerify the main entrypoint, Inky (inky.ex)

### ISSUE THREAD

**Issue by nyaray** [pappersverk/inky#11]
Re-written (again ^^) thoughts after a longer chat with @lawik

In Inky, we'd expose a simple API:
- `start_link(opts \\ [])`, accepts `name`
- `stop(pid | name)`
- `set_pixels(pid | name, pixels | painter, opts \\ [])`, updates genserver state either with specific pixels or by calling `painter.(x,y)` for all points in the screen, in an undefined order.

  To begin with, it only accepts an `:update` option with one of the following values
  - `:state_only`: do not push to display, just update pixel state
  - `{:timeout, :once}`: Use genserver timeouts to avoid multiple updates. When the timeout triggers, update the display if not busy. Otherwise just updates pixel state.
  - `{:timeout, :await}`: Use genserver timeouts to avoid multiple updates. When the timeout triggers, await device ready with a busy wait and then push to the display.
  - `:once`: Check if busy once, return timeout if failed, otherwise push to display. Update pixel state regardless. If there has been a timeout previously set, but that has yet to fire, it will be set again.
  - `:await`: Busy wait until you can push to display.
- `show(async \\ false)`, render pixels, blocking the client by default, the genserver always busy waits internally

**Comment by lawik** [comment]
Looks pretty good to me. The set function might be a bit overloaded with those options but with this API-surface it should be fine :)

**Comment by nyaray** [comment]
The options actually _help_ keep the api simple, as they minimise the amount of "does the thing... and also x,y in z way" functions since the options are orthogonal from _setting_ pixels. In other words, the overall api becomes simpler since the pixels are set in one way.

The word "overloaded" struck a chord with me, though... I'll update the API suggestion!

**Comment by lawik** [comment]
That API surface is more easy to understand. But maybe you were right that `set_pixels(pid, data, opts)` is all we need. So we can skip `show` and `show_async`.

I think we can just remove `set_pixel` for single pixel changes. That just encourages unoptimizable behavior.

`set_fill` is a good utility. Though I'd love to remove it just to minimize the API. I wonder if we should expose some kind of iterate-over-your-pixels-with-double-reduce functionality where you pass your own callback. Not part of this API-surface. But maybe a nice util. And then we could just have a `get_fill` util there.

So Inky would expose:
- `start_link`
- `set_pixels`

Inky.Util would expose:
- `fill(color)`
- `generate_pixels(your_fancy_function)` your fancy function takes (x, y) and returns a color atom.

I'm aware I'm going back and forth on those opts. You are making me think, I'm not sure I like it ;)

**Comment by nyaray** [comment]
> I think we can just remove set_pixel for single pixel changes. That just encourages unoptimizable behavior.

I disagree. If you set `active: false`, no internal call to `show` will be made.

> set_fill is a good utility. Though I'd love to remove it just to minimize the API. I wonder if we should expose some kind of iterate-over-your-pixels-with-double-reduce functionality where you pass your own callback. Not part of this API-surface. But maybe a nice util. And then we could just have a get_fill util there.

How about this, I'll trade my set_fill for your generate_pixels, but instead we call it `map_pixels(x,y) :: color`, how does that sound? That way, we generalise and set_fill becomes a shorthand you can throw in as a callback from that utility you mentioned... But get_fill is weird and only valid for some states and thus, not general enough to exist, imho.

> I'm aware I'm going back and forth on those opts. You are making me think, I'm not sure I like it ;)

The opts pattern is established for a reason :). EMBRACE the think-discomfort.

**Comment by lawik** [comment]
I don't mind the pattern of opts as such. Just didn't feel like the clearest and most discoverable. But I think it gives the right flexibility in this case.

We have an accord on the map_pixel 🤝
