### ISSUE TITLE
Missing dependencies?

### ISSUE THREAD

**Issue by nyaray** [pappersverk/inky#2]
I did a clean clone, fetched and built deps and tried running mix to just compile everything and got a warning.

```
Generated inky_zero_nerves app
You have configured application :nerves_firmware_ssh in your configuration file,
but the application is not available.

This usually means one of:

  1. You have not added the application as a dependency in a mix.exs file.

  2. You are configuring an application that does not really exist.

Please ensure :nerves_firmware_ssh exists or remove the configuration.

You have configured application :nerves_init_gadget in your configuration file,
but the application is not available.

This usually means one of:

  1. You have not added the application as a dependency in a mix.exs file.

  2. You are configuring an application that does not really exist.

Please ensure :nerves_init_gadget exists or remove the configuration.
```

**Comment by nyaray** [comment]
Having looked at the issue a bit more, I realise that it's just a matter of configuration not looking at the mix target. It can probably be resolved by creating template config files for the supported targets.

`config.exs` could contain something like `import_config "config.#{Mix.Project.config()[:target]}.exs"`

**Comment by lawik** [comment]
Did you fix this while working on the other stuff?

**Comment by nyaray** [comment]
Nope. It requires a bit of thought and is just a printed warning, so it can wait.
