### ISSUE TITLE
Not working with wHAT display

### ISSUE THREAD

**Issue by BrynjarM** [pappersverk/inky#27]
The library (v1.0.0) is not working with my Inky wHAT red on Raspberry Pi Zero W

If I configure it to use pHAT it works on part of the screen, so it has something to do with wHAT part of the implementation.

Verified that the screen works fine with the Python library

Small example
```
{:ok, pid} = Inky.start_link(:what, :red, %{name: InkySample})

painter = fn x, y, w, h, _pixels_so_far ->:black end

Inky.set_pixels(InkySample, painter, border: :white)
```

Error
```
16:17:31.481 [error] GenServer InkySample terminating
** (MatchError) no match of right hand side value: {:error, :transfer_failed}
    (inky) lib/hal/rpiio.ex:101: Inky.RpiIO.spi_write/3
    (inky) lib/hal/rpihal.ex:243: Inky.RpiHAL.write_command/3
    (inky) lib/hal/rpihal.ex:93: Inky.RpiHAL.do_update/5
    (inky) lib/inky.ex:165: Inky.handle_call/3
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.172.0>): {:set_pixels, #Function<11.128620087/5 in :erl_eval.expr/5>, [border: :white]}
State: %Inky.State{border: :black, display: %Inky.Display{accent: :red, height: 300, luts: <<72, 160, 16, 16, 19, 0, 0, 72, 160, 128, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 165, 0, 187, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 12, 32, 12, 6, 16, 8, 4, 4, 6, ...>>, packed_dimensions: %{height: <<44, 1>>, width: "1"}, rotation: 0, type: :what, width: 400}, hal_mod: Inky.RpiHAL, hal_state: %Inky.RpiHAL.State{display: %Inky.Display{accent: :red, height: 300, luts: <<72, 160, 16, 16, 19, 0, 0, 72, 160, 128, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 165, 0, 187, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 12, 32, 12, 6, 16, 8, ...>>, packed_dimensions: %{height: <<44, 1>>, width: "1"}, rotation: 0, type: :what, width: 400}, io_mod: Inky.RpiIO, io_state: %Inky.RpiIO.State{busy_pid: #Reference<0.269476080.1512177672.81328>, dc_pid: #Reference<0.269476080.1512177672.81326>, reset_pid: #Reference<0.269476080.1512177672.81327>, spi_pid: #Reference<0.269476080.1512177672.81331>}}, pixels: %{}, type: nil, wait_type: :nowait}
Client #PID<0.172.0> is alive

    (stdlib) gen.erl:169: :gen.do_call/4
    (elixir) lib/gen_server.ex:1007: GenServer.call/3
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir) src/elixir.erl:275: :elixir.eval_forms/4
    (iex) lib/iex/evaluator.ex:257: IEx.Evaluator.handle_eval/5
    (iex) lib/iex/evaluator.ex:237: IEx.Evaluator.do_eval/3
    (iex) lib/iex/evaluator.ex:215: IEx.Evaluator.eval/3
    (iex) lib/iex/evaluator.ex:103: IEx.Evaluator.loop/1
** (EXIT from #PID<0.172.0>) shell process exited with reason: an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, :transfer_failed}
        (inky) lib/hal/rpiio.ex:101: Inky.RpiIO.spi_write/3
        (inky) lib/hal/rpihal.ex:243: Inky.RpiHAL.write_command/3
        (inky) lib/hal/rpihal.ex:93: Inky.RpiHAL.do_update/5
        (inky) lib/inky.ex:165: Inky.handle_call/3
        (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
        (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by nyaray** [comment]
Congratulations (and apologies) and welcome to the WHAT verification team. Lars (@lawik) and I will try to keep your involvement at a minimum.

I just have to ask to verify, since I don't think Lars has tried it either... Are you on some rpi-oriented distro? The reason I ask is that we've only used it on nerves as far as I know.

Hopefully we will be able to figure this out soon. Thanks for letting us know about your issue!

**Comment by BrynjarM** [comment]
Tried it first on Nerves and then on Raspbian, same behaviour.

If I modify the size of the screen for wHAT in display.ex from (400x300) to (100x300) it renders the first 100 pixels, full height without errors. 

Also seems that https://github.com/pimoroni/inky/blob/master/library/inky/inky.py#L272 is missing in the implementation, command for wHAT and red. Not sure if its related.

**Comment by nyaray** [comment]
If you don't mind, you could edit your checked out copy of inky, adding a suitably named function after the one at https://github.com/pappersverk/inky/blob/master/lib/hal/rpihal.ex#L161 doing the equivalent of the missing spi command you found. Then you can call it after https://github.com/pappersverk/inky/blob/master/lib/hal/rpihal.ex#L91

**Comment by nyaray** [comment]
We've been meaning to port the spi command sequences but have yet to get around to it. If we're lucky, it solves your issue

**Comment by lawik** [comment]
I wonder if this was something I stripped out of my original port when I was having trouble making it work at all. I'll take a look at adding them in a branch.

**Comment by lawik** [comment]
The branch `issue-27-what-spi` has that change. So we can see if that works. It isn't the final code but should at least do the right thing.

To add it to your deps, try:

```
{:inky, github: "pappersverk/inky", ref: "issue-27-what-spi"}
```

If you can try it out that'd be much appreciated. I take no responsibility for the safety of your device ;)

**Comment by BrynjarM** [comment]
@lawik sorry for the delay, did not have a change to run it until now.

Its still failing

```
18:31:28.655 [error] GenServer InkySample terminating
** (MatchError) no match of right hand side value: {:error, :transfer_failed}
    (inky) lib/hal/rpiio.ex:101: Inky.RpiIO.spi_write/3
    (inky) lib/hal/rpihal.ex:257: Inky.RpiHAL.write_command/3
    (inky) lib/hal/rpihal.ex:93: Inky.RpiHAL.do_update/5
    (inky) lib/inky.ex:165: Inky.handle_call/3
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.175.0>): {:set_pixels, #Function<11.128620087/5 in :erl_eval.expr/5>, [border: :white]}
State: %Inky.State{border: :black, display: %Inky.Display{accent: :red, height: 300, luts: <<72, 160, 16, 16, 19, 0, 0, 72, 160, 128, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 165, 0, 187, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 12, 32, 12, 6, 16, 8, 4, 4, 6, ...>>, packed_dimensions: %{height: <<44, 1>>, width: "1"}, rotation: 0, type: :what, width: 400}, hal_mod: Inky.RpiHAL, hal_state: %Inky.RpiHAL.State{display: %Inky.Display{accent: :red, height: 300, luts: <<72, 160, 16, 16, 19, 0, 0, 72, 160, 128, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 165, 0, 187, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 12, 32, 12, 6, 16, 8, ...>>, packed_dimensions: %{height: <<44, 1>>, width: "1"}, rotation: 0, type: :what, width: 400}, io_mod: Inky.RpiIO, io_state: %Inky.RpiIO.State{busy_pid: #Reference<0.373578754.1396572167.194979>, dc_pid: #Reference<0.373578754.1396572167.194977>, reset_pid: #Reference<0.373578754.1396572167.194978>, spi_pid: #Reference<0.373578754.1396572167.194982>}}, pixels: %{}, type: nil, wait_type: :nowait}
Client #PID<0.175.0> is alive

    (stdlib) gen.erl:169: :gen.do_call/4
    (elixir) lib/gen_server.ex:1007: GenServer.call/3
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir) src/elixir.erl:275: :elixir.eval_forms/4
    (iex) lib/iex/evaluator.ex:257: IEx.Evaluator.handle_eval/5
    (iex) lib/iex/evaluator.ex:237: IEx.Evaluator.do_eval/3
    (iex) lib/iex/evaluator.ex:215: IEx.Evaluator.eval/3
    (iex) lib/iex/evaluator.ex:103: IEx.Evaluator.loop/1
** (EXIT from #PID<0.175.0>) shell process exited with reason: an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, :transfer_failed}
        (inky) lib/hal/rpiio.ex:101: Inky.RpiIO.spi_write/3
        (inky) lib/hal/rpihal.ex:257: Inky.RpiHAL.write_command/3
        (inky) lib/hal/rpihal.ex:93: Inky.RpiHAL.do_update/5
        (inky) lib/inky.ex:165: Inky.handle_call/3
        (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
        (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by BrynjarM** [comment]
@lawik, @nyaray: I think I might have spotted the remaining issue, the Python library uses _SPI_CHUNK_SIZE to split down large writes (so its not larger than 4096)
https://github.com/pimoroni/inky/blob/master/library/inky/inky.py#L350

**Comment by lawik** [comment]
Oh, right, *that* thing. Yup, also something I stripped out while trying to get things to work for the pHAT. I'll take a look when I can :) Thanks for the help tracking these down.

**Comment by lawik** [comment]
Okay, the same branch has been updated with an attempt at chunking. I haven't tried the code-path out on-device because I'm a bit pressed for time. But if you want to give it a spin, it's there.

It captures the error and retries with what I believe should be correct chunks. Much like the python-thing does. I think we might want to look before we leap rather than attempt, fail and retry later on. But first, lets see if it works :)

**Comment by BrynjarM** [comment]
@lawik thank you, it still errored out but I was able to modify it to work
https://github.com/BrynjarM/inky/commit/14f627677385f0517d70359114ec6dab97e76c9e

**Comment by lawik** [comment]
So you have it working now?

**Comment by BrynjarM** [comment]
yes

**Comment by lawik** [comment]
Toss me a PR with that change will you? I'll start cleaning it up for a proper merge.

**Comment by BrynjarM** [comment]
https://github.com/pappersverk/inky/pull/31

**Comment by lawik** [comment]
Merged. Going to do some clean-up. Thanks a lot for the help.

**Comment by lawik** [comment]
#32 is ready, want another eye on it before I push it through and see if we have anything else for a 1.0.1 release. Hope you can make do with the branch until then.
