### ISSUE TITLE
set border color at creation and after creation

### ISSUE THREAD

**Issue by nyaray** [pappersverk/inky#6]
there should be a way to set the border color like in the python lib [1]

[1] - https://github.com/pimoroni/inky/blob/master/library/inky/inky.py#L258-L267

**Comment by lawik** [comment]
There should. I set it to always be black when I was struggling to make all the details work.

Option for set_pixels?

**Comment by nyaray** [comment]
> Option for set_pixels?

Yes, but also for init.. Once we have a GenServer, we can work it in pretty easily, I think.

**Comment by nyaray** [comment]
Implemented in #25
